import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, AlertTriangle, Cpu, Database, KeyRound, LayoutDashboard, Play, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Users, WalletCards } from 'lucide-react';
import {
  AdminFinance, AdminJobStatus, AdminOverview, AdminSpec, AdminUser, AIWeightSettings, LLMProviderSettings,
  OperationSettings, URLCacheSettings, executeAdminSpec, getAdminFinance, getAdminOverview, getAdminSpecStatus,
  getAdminSpecs, getAdminTrainingStatus, getAdminUsers, getAIWeight, getLLMProvider, getOperationSettings,
  getURLCache, purgeURLCache, saveAIWeight, saveLLMProvider, saveOperationSettings, saveURLCache,
  setAdminUserStatus, testLLMProvider, trainAdminModels,
} from './api';

type Tab = 'overview'|'users'|'finance'|'operations';
const money=(n:number)=>`${new Intl.NumberFormat('vi-VN').format(n)} ₫`;
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'Chưa có';
const initialOps:OperationSettings={threatFeedSchedulerEnabled:false,openphishEnabled:false,operationalMaintenanceSchedulerEnabled:false};
const initialLLM:LLMProviderSettings={provider:'endpoint',baseUrl:'',model:'',apiKeyConfigured:false,configured:false,source:'environment',allowedProviders:['auto','adapter','local','endpoint'],allowedModels:[]};

export default function AdminConsole({currentUserId}:{currentUserId:string}){
  const [tab,setTab]=useState<Tab>('overview'); const [overview,setOverview]=useState<AdminOverview|null>(null); const [users,setUsers]=useState<AdminUser[]>([]); const [finance,setFinance]=useState<AdminFinance|null>(null);
  const [specs,setSpecs]=useState<AdminSpec[]>([]); const [jobs,setJobs]=useState<Record<string,AdminJobStatus>>({}); const [training,setTraining]=useState<AdminJobStatus>({status:'idle',progress:0});
  const [weight,setWeight]=useState<AIWeightSettings>({percent:0,minPercent:0,maxPercent:40,absoluteMaxPercent:100,mode:'shadow'}); const [weightDraft,setWeightDraft]=useState(0); const [weightMinDraft,setWeightMinDraft]=useState(0); const [weightMaxDraft,setWeightMaxDraft]=useState(40);
  const [llm,setLLM]=useState(initialLLM); const [llmDraft,setLLMDraft]=useState({provider:'endpoint' as LLMProviderSettings['provider'],baseUrl:'',model:'',apiKey:'',allowedProviders:initialLLM.allowedProviders,allowedModelsText:''});
  const [cache,setCache]=useState<URLCacheSettings>({enabled:true,ttlSeconds:900}); const [ops,setOps]=useState(initialOps);
  const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(''); const [notice,setNotice]=useState(''); const [query,setQuery]=useState(''); const timers=useRef<number[]>([]);
  const fail=(e:unknown,fallback:string)=>setNotice(e instanceof Error?e.message:fallback);
  const load=async()=>{setBusy(true);setNotice('');try{const [o,u,f,s,w,l,c,p]=await Promise.all([getAdminOverview(),getAdminUsers(),getAdminFinance(),getAdminSpecs(),getAIWeight(),getLLMProvider(),getURLCache(),getOperationSettings()]);setOverview(o);setUsers(u.users);setFinance(f);setSpecs(s.specs);setWeight(w);setWeightDraft(w.percent);setWeightMinDraft(w.minPercent);setWeightMaxDraft(w.maxPercent);setLLM(l);setLLMDraft({provider:l.provider,baseUrl:l.baseUrl,model:l.model,apiKey:'',allowedProviders:l.allowedProviders,allowedModelsText:l.allowedModels.join(', ')});setCache(c);setOps(p)}catch(e){fail(e,'Không thể tải trung tâm quản trị.')}finally{setBusy(false)}};
  useEffect(()=>{
    void load();
    const sync=()=>{if(document.visibilityState==='visible')void load()};
    window.addEventListener('focus',sync);document.addEventListener('visibilitychange',sync);
    return()=>{window.removeEventListener('focus',sync);document.removeEventListener('visibilitychange',sync);timers.current.forEach(window.clearInterval)};
  },[]);
  const visibleUsers=useMemo(()=>users.filter(u=>`${u.displayName} ${u.email} ${u.currentPlan}`.toLowerCase().includes(query.trim().toLowerCase())),[users,query]);
  const totalTasks=specs.reduce((n,s)=>n+s.tasksTotal,0), completedTasks=specs.reduce((n,s)=>n+s.tasksCompleted,0), automation=Object.values(ops).filter(Boolean).length;
  const run=async(key:string,action:()=>Promise<void>)=>{setSaving(key);setNotice('');try{await action()}catch(e){fail(e,'Thao tác quản trị thất bại.')}finally{setSaving('')}};
  const toggleUser=(u:AdminUser)=>void run(`user-${u.id}`,async()=>{const status=u.status==='active'?'suspended':'active';if(!window.confirm(`Xác nhận ${status==='suspended'?'khóa':'kích hoạt lại'} tài khoản ${u.email}?`))return;await setAdminUserStatus(u.id,status);setUsers(items=>items.map(x=>x.id===u.id?{...x,status}:x));setNotice('Đã cập nhật trạng thái tài khoản.')});
  const poll=(fn:()=>Promise<AdminJobStatus>,apply:(v:AdminJobStatus)=>void)=>{const id=window.setInterval(async()=>{try{const v=await fn();apply(v);if(['completed','error'].includes(v.status))window.clearInterval(id)}catch{window.clearInterval(id)}},3000);timers.current.push(id)};
  const executeSpec=(s:AdminSpec)=>void run(`spec-${s.id}`,async()=>{await executeAdminSpec(s.id);const next={status:'running',progress:0,message:'Đang khởi tạo…',specId:s.id} as AdminJobStatus;setJobs(v=>({...v,[s.id]:next}));poll(()=>getAdminSpecStatus(s.id),v=>setJobs(x=>({...x,[s.id]:v})))});
  const train=()=>void run('train',async()=>{await trainAdminModels();setTraining({status:'training',progress:0,message:'Đang khởi tạo pipeline…'});poll(getAdminTrainingStatus,setTraining)});
  const nav:[Tab,string,typeof Activity][]=[['overview','Tổng quan',LayoutDashboard],['users','Người dùng',Users],['finance','Tài chính',WalletCards],['operations','Vận hành',SlidersHorizontal]];
  return <section className="admin-console adminx"><aside className="admin-sidebar"><div><span className="eyebrow">PREWISE / ADMIN CENTER</span><h2>Trung tâm quản trị</h2><p>Không gian thống nhất cho hệ thống, người dùng, tài chính và vận hành kỹ thuật.</p></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{label}{id==='users'&&<b>{users.length}</b>}</button>)}</nav><div className="admin-security"><ShieldCheck/><span><b>Phiên quản trị an toàn</b><small>RBAC đang được áp dụng</small></span></div></aside>
  <article className="admin-content"><header className="admin-heading"><div><span className="eyebrow">ADMIN CONTROL PLANE</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1><p>AI {weight.percent}% · Endpoint {llm.configured?'ON':'OFF'} · Cache {cache.enabled?'ON':'OFF'} · Automation {automation}/3 · Spec {completedTasks}/{totalTasks}</p></div><button className="admin-refresh" onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?'spin':''}/>Làm mới tất cả</button></header>
  {notice&&<div className="admin-error" role="status"><AlertTriangle/>{notice}</div>}{busy&&!overview?<div className="admin-loading"><RefreshCw className="spin"/>Đang đồng bộ trung tâm quản trị…</div>:<>
  {tab==='overview'&&overview&&<><div className="metric-grid"><Metric label="Người dùng" value={overview.metrics.usersTotal} note={`${overview.metrics.activeUsers} đang hoạt động`}/><Metric label="Lượt phân tích" value={overview.metrics.scansTotal} note="Tổng lượt đã ghi nhận"/><Metric label="Rủi ro cao" value={overview.metrics.dangerousScans} note="Tín hiệu cần chú ý" danger/><Metric label="Độ trễ trung bình" value={`${overview.metrics.averageLatencyMs} ms`} note="Thời gian phản hồi"/></div><div className="admin-panels"><Panel title="Phân tích gần đây">{overview.recentScans.map(s=><div className="adminx-row" key={s.id}><span className={`risk-badge ${s.riskLevel}`}>{s.score}</span><span><b>{s.target}</b><small>{s.modality} · {date(s.createdAt)}</small></span><em>{s.riskLevel}</em></div>)}{!overview.recentScans.length&&<Empty/>}</Panel><Panel title="Tác vụ gần đây">{overview.recentJobs.map(j=><div className="adminx-row" key={j.id}><Activity/><span><b>{j.type}</b><small>{j.message||`${j.progress}%`} · {date(j.createdAt)}</small></span><em>{j.status}</em></div>)}{!overview.recentJobs.length&&<Empty/>}</Panel></div><Panel title="Model registry" extra>{overview.models.map(m=><div className="adminx-model" key={m.id}><Cpu/><span><b>{m.name}</b><small>{m.modality} · {m.status}</small></span><strong>{m.f1!=null?`F1 ${(m.f1*100).toFixed(1)}%`:'—'}</strong></div>)}{!overview.models.length&&<Empty/>}</Panel></>}
  {tab==='users'&&<><div className="adminx-tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tên, email hoặc gói…"/></label><span>{visibleUsers.length} kết quả</span></div><div className="adminx-table users"><div className="adminx-head"><span>Người dùng</span><span>Vai trò</span><span>Gói</span><span>Lượt quét</span><span>Đăng nhập cuối</span><span>Trạng thái</span></div>{visibleUsers.map(u=><div className="adminx-tr" key={u.id}><span><b>{u.displayName}</b><small>{u.email}</small></span><span>{u.role}</span><span>{u.currentPlan.toUpperCase()}</span><span>{u.scansTotal}</span><span>{date(u.lastLoginAt)}</span><span className="adminx-action"><em className={u.status}>{u.status==='active'?'Hoạt động':'Tạm khóa'}</em><button disabled={u.id===currentUserId||saving===`user-${u.id}`} onClick={()=>toggleUser(u)}>{u.id===currentUserId?'Đang dùng':u.status==='active'?'Khóa':'Kích hoạt'}</button></span></div>)}</div></>}
  {tab==='finance'&&finance&&<><div className="metric-grid"><Metric label="Tổng doanh thu" value={money(finance.summary.totalRevenueVnd)} note="Đơn đã thanh toán"/><Metric label="30 ngày gần nhất" value={money(finance.summary.revenueLast30DaysVnd)} note="Theo paid_at"/><Metric label="Đang chờ" value={money(finance.summary.pendingAmountVnd)} note={`${finance.summary.pendingOrders} đơn`}/><Metric label="Thuê bao active" value={finance.summary.activeSubscriptions} note={`${finance.summary.paidOrders} đơn đã trả`}/></div><div className="admin-panels"><Panel title="Doanh thu 6 tháng">{finance.monthlyRevenue.map(x=><div className="adminx-row" key={x.month}><WalletCards/><span><b>{x.month}</b><small>Doanh thu xác nhận</small></span><strong>{money(x.amountVnd)}</strong></div>)}</Panel><Panel title="Phân bổ gói">{finance.plans.map(p=><div className="adminx-row" key={p.tier}><Database/><span><b>{p.label}</b><small>{p.monthlyPriceVnd?`${money(p.monthlyPriceVnd)}/tháng`:'Miễn phí / liên hệ'}</small></span><strong>{finance.planDistribution[p.tier]??0}</strong></div>)}</Panel></div><div className="adminx-table orders"><div className="adminx-head"><span>Tham chiếu</span><span>Khách hàng</span><span>Gói</span><span>Số tiền</span><span>Thời gian</span><span>Trạng thái</span></div>{finance.recentOrders.map(o=><div className="adminx-tr" key={o.id}><code>{o.reference}</code><span>{o.email}</span><span>{o.planTier?.toUpperCase()||'CREDIT'}</span><b>{money(o.amountVnd)}</b><span>{date(o.paidAt||o.createdAt)}</span><em className={o.status}>{o.status}</em></div>)}</div></>}
  {tab==='operations'&&<div className="adminx-ops"><Op title="Endpoint AI OpenAI-compatible" icon={<KeyRound/>}><div className="adminx-form"><label>Provider<select value={llmDraft.provider} onChange={e=>setLLMDraft({...llmDraft,provider:e.target.value as LLMProviderSettings['provider']})}><option value="endpoint">API endpoint</option><option value="local">Local model</option><option value="adapter">Prewise adapter</option><option value="auto">Auto</option></select></label><label>Model ID<input value={llmDraft.model} onChange={e=>setLLMDraft({...llmDraft,model:e.target.value})}/></label><label className="wide">Base URL<input value={llmDraft.baseUrl} onChange={e=>setLLMDraft({...llmDraft,baseUrl:e.target.value})} placeholder="http://127.0.0.1:20128/v1"/></label>{llmDraft.provider==='endpoint'&&<label className="wide">API key<input type="password" value={llmDraft.apiKey} onChange={e=>setLLMDraft({...llmDraft,apiKey:e.target.value})} placeholder={llm.apiKeyConfigured?'Để trống để giữ khóa đã lưu':'Nhập API key'}/></label>}<label className="wide">Provider user được phép<input value={llmDraft.allowedProviders.join(', ')} onChange={e=>setLLMDraft({...llmDraft,allowedProviders:Array.from(new Set(['auto',...e.target.value.split(',').map(x=>x.trim()).filter((x):x is LLMProviderSettings['provider']=>['auto','adapter','local','endpoint'].includes(x))]))})}/></label><label className="wide">Model user được phép<input value={llmDraft.allowedModelsText} onChange={e=>setLLMDraft({...llmDraft,allowedModelsText:e.target.value})} placeholder="Để trống = mọi model; model-a, model-b"/></label></div><div className="adminx-buttons"><button onClick={()=>void run('llm',async()=>{const x=await saveLLMProvider({...llmDraft,allowedModels:llmDraft.allowedModelsText.split(',').map(x=>x.trim()).filter(Boolean),...(llmDraft.apiKey?{apiKey:llmDraft.apiKey}:{})});setLLM(x);setLLMDraft(v=>({...v,apiKey:''}));setNotice('Đã lưu và áp dụng endpoint AI.')})}>Lưu và áp dụng</button><button disabled={!llm.configured||!['endpoint','local'].includes(llm.provider)} onClick={()=>void run('test-llm',async()=>{const x=await testLLMProvider();setNotice(x.modelAvailable?'Kết nối và gọi model thành công.':'Kết nối được nhưng chưa thấy model đã chọn.')})}>Kiểm tra endpoint + model</button></div></Op>
  <Op title="AI Context Weight" icon={<SlidersHorizontal/>}><div className="adminx-range"><b>{weightDraft}%</b><label>Sàn<input type="number" min="0" max={weightMaxDraft} value={weightMinDraft} onChange={e=>{const v=Number(e.target.value);setWeightMinDraft(v);setWeightDraft(x=>Math.max(x,v))}}/></label><label>Trần<input type="number" min={weightMinDraft} max={weight.absoluteMaxPercent} value={weightMaxDraft} onChange={e=>{const v=Number(e.target.value);setWeightMaxDraft(v);setWeightDraft(x=>Math.min(x,v))}}/></label><input type="range" min={weightMinDraft} max={weightMaxDraft} value={weightDraft} onChange={e=>setWeightDraft(Number(e.target.value))}/><span>Admin {weightMinDraft}–{weightMaxDraft}% · mặc định {weightDraft}%</span><button disabled={weightDraft===weight.percent&&weightMinDraft===weight.minPercent&&weightMaxDraft===weight.maxPercent} onClick={()=>void run('weight',async()=>{const x=await saveAIWeight(weightDraft,weightMinDraft,weightMaxDraft);setWeight(x);setNotice('Đã lưu chính sách tỷ trọng AI.')})}>Lưu chính sách</button></div></Op>
  <Op title="URL Result Cache" icon={<Database/>}><div className="adminx-switchline"><span><b>{cache.enabled?'Đang bật':'Đang tắt'}</b><small>TTL {cache.ttlSeconds/60} phút</small></span><button role="switch" aria-checked={cache.enabled} onClick={()=>void run('cache',async()=>{const x=await saveURLCache(!cache.enabled);setCache(x)})}>{cache.enabled?'Tắt cache':'Bật cache'}</button><button className="danger-button" onClick={()=>{if(window.confirm('Xóa toàn bộ kết quả URL trong cache?'))void run('purge',async()=>{const x=await purgeURLCache();setNotice(`Đã xóa ${x.purged} kết quả URL khỏi cache.`)})}}>Xóa cache</button></div></Op>
  <Op title="Threat Feed & Maintenance" icon={<RefreshCw/>}><div className="adminx-switches">{([['threatFeedSchedulerEnabled','Tự cập nhật threat-feed'],['openphishEnabled','Dùng OpenPhish'],['operationalMaintenanceSchedulerEnabled','Tự dọn dữ liệu hết hạn']] as [keyof OperationSettings,string][]).map(([k,label])=><button key={k} className={ops[k]?'on':''} onClick={()=>void run('ops',async()=>{const x=await saveOperationSettings({...ops,[k]:!ops[k]});setOps(x);setNotice('Đã lưu cấu hình scheduler.')})}><b>{ops[k]?'Đang bật':'Đang tắt'}</b><span>{label}</span></button>)}</div></Op>
  <Op title="Đặc tả & thực thi tác vụ" icon={<Play/>}>{specs.map(s=>{const j=jobs[s.id];return <div className="adminx-spec" key={s.id}><span><b>{s.name}</b><small>{s.tasksCompleted}/{s.tasksTotal} tác vụ hoàn tất</small></span><meter min="0" max={s.tasksTotal||1} value={j?.progress!=null?j.progress/100*(s.tasksTotal||1):s.tasksCompleted}/><em>{j?.message||`${s.tasksRemaining} còn lại`}</em><button disabled={j?.status==='running'||saving===`spec-${s.id}`} onClick={()=>executeSpec(s)}>{j?.status==='running'?'Đang chạy…':'Thực thi'}</button></div>})}{!specs.length&&<Empty/>}</Op>
  <Op title="Huấn luyện mô hình" icon={<Cpu/>}><div className="adminx-train"><span><b>Text model</b><small>data/demo_text_training.csv</small></span><meter min="0" max="100" value={training.progress}/><em>{training.message||training.status}</em><button disabled={training.status==='training'||training.status==='running'} onClick={train}><Play/>Huấn luyện</button></div>{training.results?.map(r=><div className="adminx-result" key={r.model}><b>{r.model}</b><span>F1 {r.f1_score!=null?`${(r.f1_score*100).toFixed(2)}%`:'—'}</span><span>Accuracy {r.accuracy!=null?`${(r.accuracy*100).toFixed(2)}%`:'—'}</span></div>)}</Op></div>}
  </>}</article></section>;
}

function Metric({label,value,note,danger=false}:{label:string;value:string|number;note:string;danger?:boolean}){return <div className={`metric-card ${danger?'danger':''}`}><small>{label}</small><b>{value}</b><p>{note}</p></div>}
function Panel({title,children,extra=false}:{title:string;children:React.ReactNode;extra?:boolean}){return <section className={`admin-panel ${extra?'adminx-extra':''}`}><div className="panel-title"><div><span className="eyebrow">LIVE DATA</span><h3>{title}</h3></div></div>{children}</section>}
function Op({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="adminx-op"><header>{icon}<div><span>CONTROL PLANE</span><h2>{title}</h2></div></header>{children}</section>}
function Empty(){return <div className="admin-empty"><Database/><p>Chưa có dữ liệu.</p></div>}
