Foreground true
LogTime true
LogFile /tmp/clamd.log
PidFile /tmp/clamd.pid
DatabaseDirectory /data/prewise/clamav
LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 127.0.0.1
User clamav
MaxFileSize 64M
MaxScanSize 128M
StreamMaxLength 64M
ExitOnOOM true
