#!/usr/bin/env bash
set -Eeuo pipefail

DATA_ROOT="/data/prewise"
SECRET_FILE="${DATA_ROOT}/runtime-secrets.env"
PGDATA="${DATA_ROOT}/postgres"
CLAMAV_DATA="${DATA_ROOT}/clamav"
APP_DATA="${DATA_ROOT}/app"
PG_BIN="$(pg_config --bindir)"

mkdir -p "${DATA_ROOT}" "${PGDATA}" "${CLAMAV_DATA}" "${APP_DATA}" /tmp/nginx-client /tmp/nginx-proxy
chmod 755 "${DATA_ROOT}"
chmod 700 "${PGDATA}" "${APP_DATA}"
chown -R postgres:postgres "${PGDATA}"
chown -R clamav:clamav "${CLAMAV_DATA}"
chown -R prewise:prewise "${APP_DATA}" /tmp/nginx-client /tmp/nginx-proxy

if [[ -f "${SECRET_FILE}" ]]; then
  # The file is generated by this script and contains only shell-safe hex values.
  # shellcheck disable=SC1090
  source "${SECRET_FILE}"
else
  umask 077
  POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 32)}"
  API_KEY_PEPPER="${API_KEY_PEPPER:-$(openssl rand -hex 32)}"
  API_KEY="${API_KEY:-pw_live_$(openssl rand -hex 24)}"
  TELEMETRY_SENSOR_PEPPER="${TELEMETRY_SENSOR_PEPPER:-$(openssl rand -hex 32)}"
  printf 'POSTGRES_PASSWORD=%s\nAPI_KEY_PEPPER=%s\nAPI_KEY=%s\nTELEMETRY_SENSOR_PEPPER=%s\n' \
    "${POSTGRES_PASSWORD}" "${API_KEY_PEPPER}" "${API_KEY}" "${TELEMETRY_SENSOR_PEPPER}" \
    > "${SECRET_FILE}"
fi
chmod 600 "${SECRET_FILE}"

export POSTGRES_PASSWORD API_KEY_PEPPER API_KEY TELEMETRY_SENSOR_PEPPER
export PGPASSWORD="${POSTGRES_PASSWORD}"
export APP_ENV=production DATABASE_REQUIRE_TLS=false DATABASE_AUTO_CREATE=false SEED_DEMO_USER=false
export MCP_ALLOW_ANONYMOUS=false CLAMAV_HOST=127.0.0.1 CLAMAV_PORT=3310
export TESSERACT_LANGUAGES="${TESSERACT_LANGUAGES:-vie+eng}"
export ADAPTER_MANIFEST_PATH="${ADAPTER_MANIFEST_PATH:-/app/server/adapters/manifest.json}"
export CORS_ALLOW_ORIGINS="${CORS_ALLOW_ORIGINS:-[]}"

ENCODED_DB_PASSWORD="$(/opt/prewise-venv/bin/python -c 'import os, urllib.parse; print(urllib.parse.quote(os.environ["POSTGRES_PASSWORD"], safe=""))')"
export DATABASE_URL="postgresql+psycopg://armor:${ENCODED_DB_PASSWORD}@127.0.0.1:5432/armor?sslmode=disable"

if [[ -n "${SPACE_HOST:-}" ]]; then
  export MCP_PUBLIC_URL="${MCP_PUBLIC_URL:-https://${SPACE_HOST}}"
fi

if [[ -n "${PREWISE_PUBLIC_BASE_URL:-}" ]]; then
  PUBLIC_API_BASE="${PREWISE_PUBLIC_BASE_URL%/}"
elif [[ -n "${SPACE_HOST:-}" ]]; then
  PUBLIC_API_BASE="https://${SPACE_HOST}"
else
  PUBLIC_API_BASE="http://127.0.0.1:${PORT:-7860}"
fi
if [[ -n "${PREWISE_PUBLIC_WS_BASE_URL:-}" ]]; then
  PUBLIC_WS_BASE="${PREWISE_PUBLIC_WS_BASE_URL%/}"
else
  PUBLIC_WS_BASE="${PUBLIC_API_BASE/http:/ws:}"
  PUBLIC_WS_BASE="${PUBLIC_WS_BASE/https:/wss:}"
fi
PREWISE_PUBLIC_BASE_URL="${PUBLIC_API_BASE}" \
PREWISE_PUBLIC_WS_BASE_URL="${PUBLIC_WS_BASE}" \
  /opt/prewise-venv/bin/python /usr/local/lib/prewise/patch_next_origin.py /app/web/.next

if [[ ! -s "${PGDATA}/PG_VERSION" ]]; then
  PWFILE="$(mktemp)"
  chmod 600 "${PWFILE}"
  printf '%s' "${POSTGRES_PASSWORD}" > "${PWFILE}"
  chown postgres:postgres "${PWFILE}"
  runuser -u postgres -- "${PG_BIN}/initdb" -D "${PGDATA}" --username=postgres \
    --auth-local=trust --auth-host=scram-sha-256 --pwfile="${PWFILE}"
  rm -f "${PWFILE}"
  printf "listen_addresses = '127.0.0.1'\nport = 5432\n" >> "${PGDATA}/postgresql.conf"
fi

runuser -u postgres -- "${PG_BIN}/pg_ctl" -D "${PGDATA}" -w start
psql --host=127.0.0.1 --username=postgres --dbname=postgres \
  --set=ON_ERROR_STOP=1 --set=app_password="${POSTGRES_PASSWORD}" <<'SQL'
SELECT format('CREATE ROLE armor LOGIN PASSWORD %L', :'app_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'armor') \gexec
ALTER ROLE armor PASSWORD :'app_password';
SELECT 'CREATE DATABASE armor OWNER armor'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'armor') \gexec
SQL

/opt/prewise-venv/bin/alembic upgrade head

rm -rf /app/.aisec-data
ln -s "${APP_DATA}" /app/.aisec-data

if ! compgen -G "${CLAMAV_DATA}/*.cvd" >/dev/null && ! compgen -G "${CLAMAV_DATA}/*.cld" >/dev/null; then
  echo "Downloading initial ClamAV signatures; the first boot can take several minutes."
  freshclam --config-file=/etc/clamav/freshclam-prewise.conf || true
fi

PIDS=()
shutdown() {
  trap - TERM INT EXIT
  for pid in "${PIDS[@]:-}"; do kill "${pid}" 2>/dev/null || true; done
  runuser -u postgres -- "${PG_BIN}/pg_ctl" -D "${PGDATA}" -m fast stop >/dev/null 2>&1 || true
  wait || true
}
trap shutdown TERM INT EXIT

clamd --config-file=/etc/clamav/clamd-prewise.conf & PIDS+=("$!")
runuser -u prewise --preserve-environment -- /opt/prewise-venv/bin/uvicorn backend.main:app \
  --host 127.0.0.1 --port 8000 --proxy-headers --no-server-header --no-date-header --no-access-log & PIDS+=("$!")
runuser -u prewise --preserve-environment -- /opt/prewise-venv/bin/python -m mcp_server.server \
  --transport streamable-http --host 127.0.0.1 --port 3001 & PIDS+=("$!")
runuser -u prewise --preserve-environment -- bash -c 'cd /app/web && exec node node_modules/next/dist/bin/next start -H 127.0.0.1 -p 3000' & PIDS+=("$!")
nginx -g 'daemon off;' & PIDS+=("$!")

# Any service exiting makes the Space unhealthy; terminate the remaining peers
# so the platform can restart the complete service set coherently.
wait -n "${PIDS[@]}"
exit 1
